# Site settings
title: "Toma Itagaki"
description: "Personal website of Toma Itagaki - Co-founder and Head of Product at DeMind Inc., working on Lifestack"
url: "https://tomaitagaki.com"
baseurl: ""

# Author
author:
  name: "Toma Itagaki"
  email: "tomaitagaki@gmail.com"
  twitter: "tomaitagaki"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /writing/:title/

# Jekyll plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/
  - netlify.toml
  - node_modules/

# Collections
collections:
  posts:
    output: true
    permalink: /writing/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default" 