[build]
  publish = "_site"
  command = "bundle install && bundle exec jekyll build"

[build.environment]
  RUBY_VERSION = "3.0.6"
  NODE_VERSION = "16"

[context.production]
  command = "bundle install && bundle exec jekyll build"

[context.deploy-preview]
  command = "bundle install && bundle exec jekyll build --drafts"

[context.branch-deploy]
  command = "bundle install && bundle exec jekyll build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# [[redirects]]
#  from = "https://www.tomaitagaki.com/*"
#  to = "https://tomaitagaki.com/:splat"
#  status = 301
#  force = true