[build]
  command = "bundle exec jekyll build"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.1"
  NODE_VERSION = "18"

[[plugins]]
  package = "netlify-plugin-ruby"

[context.production]
  command = "bundle exec jekyll build"

[context.deploy-preview]
  command = "bundle exec jekyll build --drafts"

[context.branch-deploy]
  command = "bundle exec jekyll build --drafts"